### ISSUE TITLE
Call for ideas! 🔥

### ISSUE THREAD

**Issue by SeanNaren** [Lightning-AI/lightning-bolts#741]
## 🚀 Feature

We'd like to expand the component set in Bolts, aiding the community in using lightning with other cool projects. If you have any suggestions please list them below in the comments!

Even if the library does not require any form of component, I think it would be nice to have a place to store documentation on using said library with Lightning (if the maintainers of the library do not include this).

Some suggestions from the [PyTorch Ecosystem](https://pytorch.org/ecosystem/)

### Model Interpretability

https://github.com/pytorch/captum
https://torchdrift.org/

### Federated Learning/Differential Privacy

https://opacus.ai/

**Comment by Borda** [comment]
Let's first list/link interesting issues from our Bolts's backlog :rabbit:

**Comment by aniketmaurya** [comment]
Hi @SeanNaren, My idea for Bolts is to have paper implementations and add pre-trained models for various use cases.

cc: @Borda
