### ISSUE TITLE
Call for core contributors 🧙

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning-bolts#819]
## 🚀 Feature

First, we are very happy about all your contribution that the community-made so far! Unfortunately, we are getting a bit short :(
Second, we would like to re-ignite this project/repository and get it back on track with the latest research and PL API!
Third, as part o the challenge, we are going to rethink the structure and integration process to be up to date and smooth as possible (also see complementary issue #741)

### Motivation

We want to form a new contributor's team which would be willing to take (participate) this challenge of re-igniting this project in the best Lightning spirit!

### Pitch

Become a key contributor, collaborate with the best, learn and practice what you love and help us make the Lightning community an even better place!

### Alternatives

Ping @Borda on slack to chat more...

### Additional context

Note that to be part of Bolt's core is not the same group as being a Core contributor of the main PL, but it will set you on a promising track to become PL core later on...

**Comment by JVGD** [comment]
This project is far too relevant to be let go, count me in. In my view this project relevancy would go after PL itself and before other branches (such as Flash, which it is also very relevant). But for me, as a full time deep learning researcher, this is of more utility.

**Comment by Borda** [comment]
@JVGD really happy to hear such nice words and the high value of Bolts! Let's see if we have a few more people and then we can have a join call to chat what we can do together... :rabbit:

**Comment by oke-aditya** [comment]
Hi. While I have been inactive in PL space.  I'm heavily intrested in this project :) 

I would be glad to join redevelopment of bolts.

**Comment by likith012** [comment]
Hi there, I am interested too. The PL project has made my life much easier and I am willing to do the same to others through this PL bolts project.

**Comment by Ce11an** [comment]
Hey!

Would also love to work on this project. Count me in 😆

**Comment by ArnolFokam** [comment]
Hi,

Count me in as well! 💪

**Comment by shenoynikhil** [comment]
Hi All,

Would love to work on this. Count me in.

**Comment by kevinpmcgee14** [comment]
Hi,

Very interested in this project. Would love to contribute!

**Comment by Borda** [comment]
Hi everyone, a giant thank you for your positive response, we really appreciate it and will follow up on it, just need a bit more time to resolve other priority issues and will ping you soon with some thoughts and details... :rabbit:

**Comment by otaj** [comment]
Hi everyone, we're very sorry for the delay!

If you are still interested (and we hope you are), can you please ping either me or @Borda on Pytorch Lightning slack where we will discuss the battle plan in more depth? My Slack username is `@Ota`, @Borda's Slack username is `@Jirka`

Thank you very much!

**Comment by Borda** [comment]
@JVGD I see multiple Javier on our slack, so not sure which one is you, could you pls ping me if you are still interested? :rabbit:

**Comment by shivammehta007** [comment]
Hello! I would love to be a part of this to learn and help bolt! :D

**Comment by otaj** [comment]
Hi @shivammehta007, I'm already counting with you, you're already in all the communications we have :muscle: But thank you!

**Comment by nishantb06** [comment]
Hi , would love to be a part of this and help develop bolts ⚡️!!

**Comment by Atharva-Phatak** [comment]
@otaj If this is still open, I would like to help you develop bolts.

**Comment by otaj** [comment]
Hi @Atharva-Phatak, absolutely! Thank you very much for your interest! Could you ping me on community Slack and I will add you to our channel? Thank you!
