### ISSUE TITLE
Input array should be flattened before running through the model

### ISSUE THREAD

**Issue by greydanus** [Lightning-AI/lightning-bolts#850]
The input `x` is being flattened (eg. `x = x.view(x.size(0), -1)`) in `validation_step` and `train_step` but not in `test_step`. I think that, for the sake of consistency, this operation should be added to `test_step`.

https://github.com/Lightning-AI/lightning-bolts/blob/5481b6e8337f4ca1381a9f0d8688f13781ef738e/pl_bolts/models/regression/linear_regression.py#L91

**Comment by otaj** [comment]
Hi, @greydanus! We are currently going through a major revision. Please, give us some time to finalize the revision, or, sign up for the part of the revision (we're going to more than welcome every helping hand :zap:) and fix possible old bugs that you've discovered while doing that revision. The revision issue is #839 :nut_and_bolt:
