### ISSUE TITLE
Keyword arguments to Faster RCNN if not passing custum backbone.

### ISSUE THREAD

**Issue by toddChavezz** [Lightning-AI/lightning-bolts#852]
## 🚀 Feature

One should be able to pass keyword arguments to Faster RCNN also if one does not have a custom backbone (which does not work so far).

### Motivation

This should be possible as it is in the case if one passes a custom backbone, for example in line 108.

### Pitch

One can just add **kwargs in pl_bolts.models.detection.faster_rcnn.faster_rcnn_module.py line 84 as the called method from torchvision already takes keyword arguments and passes them in the correct way.

**Comment by toddChavezz** [comment]
I would also like to take this myself.

**Comment by luca-medeiros** [comment]
This module is currently under review! You can write a comment here https://github.com/Lightning-AI/lightning-bolts/issues/839 and let @otaj know that you would like to work on it. While checking it for issues you can implement your idea and send a PR. Thanks!

**Comment by otaj** [comment]
Hi, @toddChavezz! @luca-medeiros is absolutely right, we are currently going through a major revision. Please, hold on to the feature requests until we're done with the revision, or, sign up for the part of the revision (we're going to more than welcome every helping hand :zap:) and add possible new features that seem to make sense to you while doing that revision.
