### ISSUE TITLE
AE.from_pretrained fails on windows

### ISSUE THREAD

**Issue by mlamarre** [Lightning-AI/lightning-bolts#876]
## 🐛 Bug

`AE.from_pretrained` fails on windows because using `os.path.join` on a web url.

In `\pl_bolts\models\autoencoders\basic_ae\basic_ae_module.py`

```
pretrained_urls = {
        'cifar10-resnet18': os.path.join(_HTTPS_AWS_HUB, 'ae/ae-cifar10/checkpoints/epoch%3D96.ckpt'),
    }
```
### To Reproduce 
On Windows:
```
from pl_bolts.models.autoencoders import AE
ae = ae.from_pretrained('cifar10-resnet18')
```

### Environment

- PyTorch Version (e.g., 1.0): 3.7
- OS (e.g., Linux): Windows

**Comment by otaj** [comment]
Hi @mlamarre, this has already been fixed over a year ago in #652. However, due to bringing it to our attention, I found one another occurrence that needed fixing.
